# Generated by Django 6.0.2 on 2026-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="curso",
            field=models.CharField(default="Sin Curso", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("examen", "Examen"),
                    ("quiz", "Quiz"),
                    ("taller", "Taller"),
                    ("proyecto", "Proyecto"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
    ]
