# Generated by Django 6.0.2 on 2026-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("hecha", "Hecha"),
                    ("pospuesta", "Pospuesta"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
