# Generated by Django 6.0.2 on 2026-03-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_add_estado_to_tarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="nota",
            field=models.TextField(blank=True, default=""),
        ),
    ]
