# Generated by Django 6.0.2 on 2026-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_actividad_curso_actividad_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarea",
            old_name="titulo",
            new_name="nombre",
        ),
        migrations.RemoveField(
            model_name="tarea",
            name="estado",
        ),
        migrations.AddField(
            model_name="tarea",
            name="actualizada_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="horas_estimadas",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
