# Generated by Django 6.0.2 on 2026-02-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_rename_titulo_tarea_nombre_remove_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha')], default='pendiente', max_length=20),
        ),
    ]
