# Generated by Django 6.0.2 on 2026-02-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_tarea_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("hecha", "Hecha")],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
