# Generated by Django 6.0.2 on 2026-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="daily_hour_limit",
            field=models.FloatField(default=6),
        ),
    ]
